spring.application.name=sb-ecom

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:das

#____________________________________________________________________________________________
#MySQL Database Connection


#spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
#spring.datasource.username=root
#spring.datasource.password=R12tw1kd@$my$ql
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#____________________________________________________________________________________________


#____________________________________________________________________________________________
#PostgresSQL Database Connection


spring.datasource.url=jdbc:postgresql://mysbecomdb.cnesgam0u0po.eu-north-1.rds.amazonaws.com:5432/myApp
spring.datasource.username=postgres
spring.datasource.password=R12tw1k2403$be(0m
#spring.datasource.password=p0$t$ql


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#____________________________________________________________________________________________



project.image=images/

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=create-drop


spring.app.jwtSecret=mySecretKey1234567rittwikdas7654321abksofjfogognpdpenhwkiiugo29y84ldnlor4y49
spring.app.jwtExpirationMs=3000000

spring.ecom.app.jwtCookieName=springBootEcom

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.sql=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.ecommerce.project=DEBUG

#Required, if using Elastic Beanstalk
server.port=5000